//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appearance
    {
        public int yearID { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public string playerID { get; set; }
        public int G_all { get; set; }
        public Nullable<int> GS { get; set; }
        public Nullable<int> G_batting { get; set; }
        public Nullable<int> G_defense { get; set; }
        public Nullable<int> G_p { get; set; }
        public Nullable<int> G_c { get; set; }
        public Nullable<int> G_1b { get; set; }
        public Nullable<int> G_2b { get; set; }
        public Nullable<int> G_3b { get; set; }
        public Nullable<int> G_ss { get; set; }
        public Nullable<int> G_lf { get; set; }
        public Nullable<int> G_cf { get; set; }
        public Nullable<int> G_rf { get; set; }
        public Nullable<int> G_of { get; set; }
        public Nullable<int> G_dh { get; set; }
        public Nullable<int> G_ph { get; set; }
        public Nullable<int> G_pr { get; set; }
    }
}
