//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batting
    {
        public string playerID { get; set; }
        public int yearID { get; set; }
        public int stint { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public int G { get; set; }
        public int AB { get; set; }
        public int R { get; set; }
        public int H { get; set; }
        public int C2B { get; set; }
        public int C3B { get; set; }
        public int HR { get; set; }
        public Nullable<int> RBI { get; set; }
        public Nullable<int> SB { get; set; }
        public Nullable<int> CS { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> SO { get; set; }
        public Nullable<int> IBB { get; set; }
        public Nullable<int> HBP { get; set; }
        public Nullable<int> SH { get; set; }
        public Nullable<int> SF { get; set; }
        public Nullable<int> GIDP { get; set; }
    }
}
