//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldingYear
    {
        public string PlayerID { get; set; }
        public int Year { get; set; }
        public string Team { get; set; }
        public short Posn { get; set; }
        public string Lg { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<short> g { get; set; }
        public Nullable<double> inn { get; set; }
        public Nullable<short> po { get; set; }
        public Nullable<short> a { get; set; }
        public Nullable<short> e { get; set; }
        public Nullable<short> dp { get; set; }
        public Nullable<short> Rtot { get; set; }
        public Nullable<short> RtotYr { get; set; }
        public Nullable<short> Skill { get; set; }
    }
}
