//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitching
    {
        public string playerID { get; set; }
        public int yearID { get; set; }
        public int stint { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public int W { get; set; }
        public int L { get; set; }
        public int G { get; set; }
        public int GS { get; set; }
        public int CG { get; set; }
        public int SHO { get; set; }
        public int SV { get; set; }
        public int IPouts { get; set; }
        public int H { get; set; }
        public int ER { get; set; }
        public int HR { get; set; }
        public int BB { get; set; }
        public int SO { get; set; }
        public Nullable<double> BAOpp { get; set; }
        public Nullable<double> ERA { get; set; }
        public Nullable<int> IBB { get; set; }
        public Nullable<int> WP { get; set; }
        public Nullable<int> HBP { get; set; }
        public Nullable<int> BK { get; set; }
        public Nullable<int> BFP { get; set; }
        public Nullable<int> GF { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> SH { get; set; }
        public Nullable<int> SF { get; set; }
        public Nullable<int> GIDP { get; set; }
        public string lahmanID { get; set; }
    }
}
