//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int yearID { get; set; }
        public string lgID { get; set; }
        public string teamID { get; set; }
        public string franchID { get; set; }
        public string divID { get; set; }
        public int Rank { get; set; }
        public string Ghome { get; set; }
        public string DivWin { get; set; }
        public string WCWin { get; set; }
        public string LgWin { get; set; }
        public string WSWin { get; set; }
        public string name { get; set; }
        public string park { get; set; }
        public string attendance { get; set; }
        public int BPF { get; set; }
        public int PPF { get; set; }
        public string teamIDBR { get; set; }
        public string teamIDlahman45 { get; set; }
        public string teamIDretro { get; set; }
    }
}
