//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTeam
    {
        public int yearID { get; set; }
        public string teamID { get; set; }
        public string ZTeam1 { get; set; }
        public string lgID { get; set; }
        public string LineName { get; set; }
        public string City { get; set; }
        public string NickName { get; set; }
        public bool UsesDH { get; set; }
    }
}
